### PR TITLE
Fix for not saving page height and page deletion blackout issue

### LINKED ISSUE #1093: [Portal] Error occur when deleting a newly created Dashboard Page
**Description:**
>The browser blackout when deleting a new Portal Dashboard Page.

**Suggested Labels:**
UI

**Suggested Assignees:**
@TanyaM 

**Affected Product Version:**
sp-4.4.0

**OS, DB, other environment details and versions:** 
> Ubuntu 18.04.1
>Google Chrome : Version 69.0.3497.92    

**Steps to reproduce:**
1. Create a new Dashboard
2. Create a new Page in Dashboard
3. Delete that page

### PR DESCRIPTION
**Pull request by LakshanKarunathilake**

### CODE REVIEW

File: components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx [hunk 1]
```diff
@@ -102,12 +102,16 @@ export default class DashboardRenderer extends Component {
...
             // Check whether the page height is difference for the same page.
-            let newHeight = nextProps.dashboard.pages.find(p => p.id === nextProps.pageId).height;
-            if (this.pageHeight !== newHeight) {
-                this.pageHeight = newHeight;
-                this.destroyGoldenLayout();
-                return true;
-            }
+            let changingPage = nextProps.dashboard.pages.find(p => p.id === nextProps.pageId);
+            let newHeight = (changingPage === undefined) ? undefined:changingPage.height;
+            // let newHeight = nextProps.dashboard.pages.find(p => p.id === nextProps.pageId).height;
```
Comment (TanyaM) [inline components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx]: Remove the commented line

File: components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx [hunk 2]
```diff
@@ -102,12 +102,16 @@ export default class DashboardRenderer extends Component {
         }
         if (this.props.pageId === nextProps.pageId) {
             // Check whether the page height is difference for the same page.
-            let newHeight = nextProps.dashboard.pages.find(p => p.id === nextProps.pageId).height;
-            if (this.pageHeight !== newHeight) {
-                this.pageHeight = newHeight;
-                this.destroyGoldenLayout();
-                return true;
-            }
+            let changingPage = nextProps.dashboard.pages.find(p => p.id === nextProps.pageId);
```
Comment (TanyaM) [inline components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx]: Not required to assign to a new variable as changingPage is not used elsewhere.

Comment (LakshanKarunathilake) [reply components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx]:
```suggestion
            let changingPage = nextProps.dashboard.pages.find(p => p.id === nextProps.pageId);
            let newHeight = (changingPage === undefined) ? undefined:changingPage.height;
```

changingPage variable is used in the next line in two places to verify whether its undefined and for the assigning of height
