### PR TITLE
Show a delete confirmation message when delete page is clicked in Dashboard Designer

### LINKED ISSUE #767: In DashBoard designer, Delete button for a page should confirm from the user before deleting.
**Description:**
In DashBoard designer, Delete button for a page should confirm from the user before deleting. Because if one user mistakenly clicked delete button, there is no way to undo.

**Suggested Labels:**
Improvement

**Affected Product Version:**
SP Version - wso2sp-4.0.0-beta3
Dashboard Version - v4.0.0.beta4

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Steps to reproduce:**
Create new dashboard called Sales Statistics.
Create some pages.
Delete one page.

### PR DESCRIPTION
**Pull request by CharukaK**
## Purpose
resolves #767 

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Test environment
Node.JS v8.5.0, NPM v5.3.0

### CODE REVIEW

File: components/dashboards-web-component/src/designer/components/PageEntry.jsx [hunk 1]
```diff
@@ -17,67 +17,38 @@
...
+import Dialog from 'material-ui/Dialog';
+import FlatButton from 'material-ui/FlatButton';
 
 const styles = {
     pageCard: {
         backgroundColor: '#17262e',
-        marginBottom: '5px'
-    }
+        marginBottom: '5px',
+        showDeletePageEntry: false,
```
Comment (lasanthaS) [inline components/dashboards-web-component/src/designer/components/PageEntry.jsx]: Shall we move this to state instead of here?

File: components/dashboards-web-component/src/designer/components/PageEntry.jsx [hunk 2]
```diff
@@ -94,15 +65,19 @@ export default class PageEntry extends Component {
         }
     }
 
+    handleClose() {
```
Comment (lasanthaS) [inline components/dashboards-web-component/src/designer/components/PageEntry.jsx]: Since the handleClose is simple function, let's move this as a lamda in line 100.
